export const ROUTES = {
  home: '/',
  signIn: '/sign-in',
  register: '/register',
  verifyAccount: '/verify-account',
  forgotPassword: '/forgot-password',
  pois: '/pois',
  poi: (id: string | number) => `/pois/${id}`,
  plan: '/plan',
  itinerary: (id: string | number) => `/itinerary/${id}`,
  tours: '/tours',
  tour: (id: string | number) => `/tours/${id}`,
  tourBooking: (id: string | number) => `/tours/${id}/book`,
  checkoutResult: '/checkout/result',
  bookingTicket: (ticketId: string | number) => `/bookings/${encodeURIComponent(ticketId)}/ticket`,
  partner: {
    dashboard: '/partner',
    register: '/partner/register',
    application: '/partner/application',
    resubmitApplication: '/partner/application/resubmit',
  },
  account: {
    profile: '/account/profile',
    preferences: '/account/preferences',
    security: '/account/security',
    trips: '/account/trips',
    tripReview: (tripId: string | number) => `/account/trips/${encodeURIComponent(tripId)}/review`,
  },
  admin: {
    login: '/admin/login',
    forgotPassword: '/admin/forgot-password',
    accountSecurity: '/admin/account/security',
    dashboard: '/admin',
    auditLogs: '/admin/audit-logs',
    tourReviews: '/admin/tours/reviews',
    tourReview: (id: string) => `/admin/tours/reviews/${id}`,
    createPoi: '/admin/catalogue/points-of-interest/new',
    algorithmParameters: '/admin/settings/algorithm-parameters',
  },
} as const;
