/**
 * English resource strings for Tour Operator Customer Bookings (UC-40, UC-41, UC-42).
 * Follows Report 3 SRS V2 CR-09 (English UI & resource file requirement).
 */
export const bookingEn = {
  header: {
    title: 'Customer Booking Management',
    useCaseTag: 'UC-40',
    subtitle: 'Monitor and look up bookings for tour packages under your management.',
    toursLink: 'Tours',
    dashboardLink: 'Dashboard',
  },
  notices: {
    pendingBackendTitle: 'Awaiting Backend API Integration',
    pendingBackendDescription:
      'Customer booking management is awaiting Backend API integration. Booking cancellation and refund initiation actions are safely locked in production mode to maintain financial data integrity.',
    demoTitle: 'Demo Preview Mode (Fixtures) — Data provided for UI evaluation.',
    demoBadge: 'Demo Active',
  },
  summary: {
    totalBookings: 'Total Bookings',
    totalBookingsSubtitle: 'Matching current filters',
    totalParticipants: 'Total Participants',
    totalParticipantsSubtitle: 'Joined travelers',
    confirmedRevenue: 'Confirmed Revenue',
    confirmedRevenueSubtitle: 'Confirmed & completed bookings',
  },
  filters: {
    tour: 'Tour Package',
    allTours: 'All Tour Packages',
    status: 'Booking Status',
    allStatuses: 'All Statuses',
    departureStartDate: 'Departure from date',
    departureEndDate: 'To date',
    searchPlaceholder: 'Search booking code (BK-...) or contact name',
    searchAriaLabel: 'Search customer bookings',
    reset: 'Reset',
    apply: 'Apply Filter',
  },
  list: {
    loading: 'Loading customer bookings...',
    emptyTitle: 'No customer bookings found',
    emptyDescription: 'No bookings match your current filter criteria.',
    emptyNoBackend: 'System is not yet connected to live Backend data.',
    tableHeaders: {
      bookingCode: 'Booking Code',
      tourName: 'Tour Package',
      departureDate: 'Departure Date',
      contact: 'Contact Person',
      paxCount: 'Pax',
      totalAmount: 'Total Amount',
      status: 'Status',
      checkIn: 'Check-in',
      actions: 'Actions',
    },
    viewDetail: 'Details',
    pagination: {
      showing: 'Showing',
      to: 'to',
      of: 'of',
      bookings: 'bookings',
      page: 'Page',
      previous: 'Previous',
      next: 'Next',
    },
  },
  statuses: {
    Confirmed: 'Confirmed',
    PendingPayment: 'Pending Payment',
    Cancelled: 'Cancelled',
    Completed: 'Completed',
  },
  checkInStatuses: {
    CheckedIn: 'Checked In',
    NotCheckedIn: 'Not Checked In',
  },
  paxTypes: {
    Adult: 'Adult',
    Child: 'Child',
    yearsOld: 'years old',
  },
  detail: {
    title: 'Booking Details',
    closeAria: 'Close details drawer',
    tourInfo: 'Tour Information',
    tourName: 'Tour Package',
    departureDate: 'Departure Date',
    checkInStatus: 'Check-in Status',
    qrTicket: 'QR E-Ticket',
    qrValid: 'Valid (Active)',
    qrInvalid: 'Unavailable / Cancelled',
    createdAt: 'Booking Created At',
    contactInfo: 'Contact Information',
    fullName: 'Full Name',
    phone: 'Phone Number',
    email: 'Email',
    participantsList: 'Participant List',
    personCount: 'passengers',
    paymentInfo: 'Payment Information (Read-Only)',
    immutableBadge: 'Immutable',
    totalAmount: 'Total Amount',
    couponUsed: 'Applied Coupon',
    paidAmount: 'Paid Amount',
    paymentChannel: 'Payment Channel',
    transactionRef: 'Transaction Reference',
    verifiedAt: 'Verification Time',
    refundRecord: 'Refund Record',
    refundAmount: 'Refund Amount',
    refundChannel: 'Refund Channel',
    gatewayRef: 'Gateway Reference',
    refundNotes: 'Notes',
    cancellationRecord: 'Cancellation Record',
    cancellationReason: 'Cancellation Reason',
    cancelledAt: 'Cancelled At',
    closeBtn: 'Close',
    cancelBookingBtn: 'Cancel Booking (UC-41)',
    refundBtn: 'Initiate Refund (UC-42)',
    notCancellableTooltip: 'This booking is not eligible for cancellation',
    notRefundableTooltip: 'This booking is not eligible for refund',
    productionLockedTooltip: 'Action is locked pending Backend API integration',
  },
  cancelDialog: {
    title: 'Cancel Booking',
    subtitle: 'Confirm cancellation and calculate applicable refund policy (UC-41).',
    closeAria: 'Close dialog',
    tourLabel: 'Tour Package:',
    departureLabel: 'Departure Date:',
    contactLabel: 'Representative:',
    participantsLabel: 'Participants:',
    passengers: 'passengers',
    totalLabel: 'Total Amount:',
    paidLabel: 'Paid Amount:',
    refundPreviewHeader: 'Estimated Refund Policy (Demo preview)',
    estimatedRefundLabel: 'Estimated Refund Amount:',
    refundNotice:
      '* Refund will be automatically issued to the original payment channel in accordance with policy. In production, final refund amounts are determined by the Backend.',
    reasonTypeLabel: 'Cancellation Reason Category',
    reasonDetailLabel: 'Cancellation Reason Details',
    reasonDetailRequired: '* (Required)',
    reasonDetailPlaceholder: 'Enter detailed cancellation reason for audit trail...',
    closeBtn: 'Close',
    confirmBtn: 'Confirm Cancellation',
    processingBtn: 'Processing...',
  },
  refundDialog: {
    title: 'Initiate Refund for Booking',
    subtitle:
      'Request refund through original payment gateway according to cancellation policy (UC-42).',
    closeAria: 'Close dialog',
    bookingCodeLabel: 'Booking Code:',
    tourLabel: 'Tour Package:',
    departureLabel: 'Departure Date:',
    paidLabel: 'Customer Paid Amount:',
    channelLabel: 'Refund Payment Channel:',
    computationHeader: 'Refund Settlement (Demo preview)',
    policyLabel: 'Policy:',
    deductionLabel: 'Deduction / Cancellation Fee:',
    refundableLabel: 'Net Refundable Amount:',
    immutableNotice:
      '* Original payment transaction remains immutable. Refund creates an independent record (settled by Backend in production).',
    existingNoticeTitle: 'Integrity Notice:',
    existingNoticeBody: 'This booking already has a refund record',
    notesLabel: 'Refund Notes (Optional)',
    notesPlaceholder: 'Enter settlement notes or audit reference information...',
    closeBtn: 'Close',
    confirmBtn: 'Initiate Refund',
    processingBtn: 'Initiating...',
  },
  messages: {
    MSG126: 'Access denied. You can only view and manage bookings for your own tours.',
    MSG29: 'Invalid date range. Departure start date must be before or equal to end date.',
    MSG128: 'No customer bookings found matching the current filter criteria.',
    MSG127: 'System encountered an error. Please try again later.',
    MSG123: 'Cancellation reason details cannot be empty.',
    MSG133: 'Booking is already cancelled/completed or a refund request already exists.',
    MSG95: 'Customer has already checked in for the tour. This booking cannot be cancelled.',
    MSG82: 'The cancellation deadline for this tour package has passed.',
    MSG81: 'Customer booking cancelled successfully.',
    MSG83: 'Booking refund request has been initiated successfully.',
    MSG84: 'Booking does not have a valid payment transaction or is not eligible for refund.',
    MSG89: 'Payment gateway timed out. Please try again or check refund queue status.',
    MSG153: 'Refund initiation could not be completed immediately; queued for retry.',
    PENDING_BE_INTEGRATION:
      'Customer booking management is awaiting Backend API integration. No live server data available.',
  },
} as const;

export type BookingResources = typeof bookingEn;
